# Generated by Django 4.1 on 2022-08-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legalname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('systeminfo', models.TextField()),
                ('is_opened', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Notification',
                'verbose_name_plural': 'Site Notifications',
            },
        ),
    ]
