# Generated by Django 4.1 on 2022-08-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='systeminfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
